<?php
print_r($_POST);
?>
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="./assets/js/script.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>



    <div class="container-fluid">
        <div class="row">


            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

                <form class="row row-cols-lg-auto g-3 align-items-center" method="post" action="">

                    <div class="row mt-2">
                        <h3 class="text-center">Settings</h3>
                        <div class="col-6 mt-2">
                            <select class="form-select" aria-label="Default select example" name="tag">
                                <option selected>Tags</option>
                                <option>With Tag</option>
                                <option>Without Tag</option>
                            </select>
                        </div>
                        <div class="col-6 mt-2"> <input type="text" class="form-control" name="Dprice" placeholder="Default Price"></div>
                        <div class="col-6 mt-2"> <input type="text" class="form-control" name="DStock" placeholder="Default Stock"></div>

                        <div class="col-6 mt-2"> <input type="text" class="form-control" name="Dzipcode" placeholder="Default Zipcode"></div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-success mt-3 text-center p-2" name="action" value="add" id="aaddproduct">Save Setting</button>
                        </div>
                </form>


        </div>
    </div>

    </main>
    </div>
    </div>
</body>

</html>