<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Product Listing</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <div class="h2 text-center text-primary">Product Listing</div><br>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Product Name</th>
        <th scope="col">Description</th>
        <th scope="col">Tags</th>
        <th scope="col">Price</th>
        <th scope="col">Stock</th>

      </tr>
    </thead>
    <tbody>
      <?php
      // echo "<pre>";
      // print_r($arr2);
      $htm = "";
      foreach ($arr2 as $key => $value) {
        $htm .= "
          <tr>
            <th scope='row'>$value->Name</th>
            <td>$value->Description</td>
            <td>$value->Tags</td>
            <td>$value->Price</td>
            <td>$value->Stock</td>
        </tr>";
      }
      echo $htm;
      ?>

    </tbody>
  </table>

</body>

</html>