<?php
echo "<pre>";
print_r($_POST);
echo "</pre>";

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../../public/assest/stylelogin.css">
</head>

<body>
    <div class="login-page">
        <div class="form">
            <!-- <form class="register-form"  method="post">
                <input type="text" placeholder="name" />
                <input type="password" placeholder="password" />
                <input type="text" placeholder="email address" />
                <button>create</button>
                <p class="message">Already registered? <a href="">Sign In</a></p>
            </form> -->
            <form class="login-form" method="post" action="">
                <input type="text" placeholder="username" name="name"/>
                <input type="password" placeholder="password" name="password"/><label>use password as login</label>
                <button name="login" value="login">login</button>
                <p class="message">Not registered? <a href="http://localhost:8080/signup/login">Create an account</a></p>
            </form>
        </div>
    </div>
</body>

</html>