<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD COMPONENT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>
    <h1 class="text-primary">add component</h1>
    <form action="" method="post">

        <div class="row">
            <div class="col-2">

                <select name="controller" class="form-select" id="cars">
                    <?php
                    $htm = "";
                    $helper = new \App\Components\Helper();
                    $arr = $helper->getControllerName();
                    foreach ($arr as $kye => $value) {
                        $htm .= "
                <option value=" . $value . ">" . $value . "</option>
                ";
                    }
                    echo $htm;
                    ?>
                    <option value="volvo" selected>Choose Controller</option>
                </select>
            </div>

            <div class="col-2">
                <input type="text" id="" name="action" placeholder="enter action"><br><br>

            </div>


        </div>
        <div class="col-6">
            <br><input type="submit" class="btn btn-outline-info" value="Add" name="action1">

        </div>
    </form>
</body>

</html>