<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <div class="h1 text-primary text-center">Welcome to Store</div>

    <div class="center mt-5 d-flex justify-content-center">
        <button type="button" class="btn btn-outline-primary"><a role="button" href="http://localhost:8080/products/products" class="btn active">ADD PRODUCTS</a></button>
        <button type="button" class="btn btn-outline-secondary"><a role="button" href="http://localhost:8080/orders/order" class="btn active">ADD ORDER</a></button>
        <button type="button" class="btn btn-outline-success"><a role="button" href="http://localhost:8080/products/productlist" class="btn active">LIST PRODUCT</a></button>
        <button type="button" class="btn btn-outline-danger"><a role="button" href="http://localhost:8080/orders/orderlist" class="btn active">LIST ORDER</a></button>
        <button type="button" class="btn btn-outline-warning"><a role="button" href="http://localhost:8080/setting/setting" class="btn active">SETTING</a></button>
        <button type="button" class="btn btn-outline-info"><a role="button" href="http://localhost:8080/secure/addrole" class="btn active">Add Role</a></button>
        <button type="button" class="btn btn-outline-dark"><a role="button" href="http://localhost:8080/secure/addcomponent" class="btn active">Add Component</a></button>
        <button type="button" class="btn btn-outline-info"><a role="button" href="http://localhost:8080/secure/acl" class="btn active">Add ACL</a></button>
    </div>

</body>

</html>