<!-- // echo "<pre>";
// print_r($_POST);
// echo "</pre>"; -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <link rel="stylesheet" href="">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" href="../../../public/assest/style.css">
    <script src="../../../public/assest/script.js"></script>
</head>

<body>
    <section class="h-100 h-custom" style="background-color: #8fc4b7;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp" class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;" alt="Sample photo">

                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">User Registration</h3>

                            <form class="px-md-2" action="" method="post">

                                <div class="form-outline">
                                    <input type="text" id="form3Example1q" class="form-control" name="name" />
                                    <label class="form-label" for="form3Example1q">Name</label>
                                </div>

                                <div class="row">
                                    <div class="col">

                                        <div class="form-outline datepicker">
                                            <input type="text" class="form-control" id="exampleDatepicker1" name="email" />
                                            <label for="exampleDatepicker1" class="form-label">Email</label>
                                        </div>

                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col">

                                        <div class="form-outline">
                                            <input type="password" id="form3Example1w" class="form-control " name="password" />
                                            <label class="form-label" for="form3Example1w">Password</label>
                                        </div>

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">

                                        <div class="form-outline">
                                            <input type="password" id="form3Example1w1" class="form-control m1" name="cpassword" />
                                            <label class="form-label" for="form3Example1w">Confirm Password</label>
                                        </div>
                                        <label id="result" class="lead"></label>
                                    </div>
                                </div>
                                <input type="checkbox" onclick="myFunction()" class="h1"><label class="lead ml-2 ">Show Password</label>
                                <script>
                                    function myFunction() {
                                        var x = document.getElementById("form3Example1w1");
                                        if (x.type === "password") {
                                            x.type = "text";
                                        } else {
                                            x.type = "password";
                                        }
                                    }

        
                                    
                                </script>
                                <div class="d-flex align-items-center justify-content-center">
                                    <button type="submit" name="action" value="register" id="register"class="btn btn-success btn-lg mb-4 mt-2 d-flex justify-content-center">Create Account</button>
                                </div>

                                <div class="row">
                                    <div class="col d-flex align-items-center justify-content-center">
                                        <a href="http://localhost:8080/login/login" class="lead">Already have an account?</a>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>