<?php
echo "<pre>";
print_r($_POST);
echo "</pre>";

?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<script type="text/javascript" src="./../../../public/assest/style.css"></script>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>


<div class="container">
	<div class="row centered-form">
		<div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Student Informration</h3>
				</div>
				<div class="panel-body">
					<form role="form" method="post" action="">
						<div class="row">
							<div class="col">
								<div class="form-group">
									<input type="number" name="rollNo" id="first_name" class="form-control input-sm floatlabel" placeholder="Roll No">
								</div>
							</div>
							
						</div>

						<div class="form-group">
							<input type="test" name="name" id="email" class="form-control input-sm" placeholder="Name">
						</div>

						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6">
								<div class="form-group">
									<input type="text" name="class" id="password" class="form-control input-sm" placeholder="Class">
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6">
								<div class="form-group">
									<input type="test" name="marks" id="password_confirmation" class="form-control input-sm" placeholder="Marks">
								</div>
							</div>
						</div>

						<input type="submit" name="Register" value="Register" class="btn btn-info btn-block">

					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<body>

</body>

</html>


<!------ Include the above in your HEAD tag ---------->