<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!--author:starttemplate-->
<!--reference site : starttemplate.com-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords"
          content="unique login form,leamug login form,boostrap login form,responsive login form,free css html login form,download login form">
    <meta name="author" content="leamug">
    <title>Unique Login Form | Bootstrap Templates</title>
    <link href="css/style.css" rel="stylesheet" id="style">
    <link rel="stylesheet" href="../../../public/assest/loginstyle.css">
    <!-- Bootstrap core Library -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!-- Google font -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"> -->
    <!-- Font Awesome-->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="../../../public/assest/script.js"></script>

</head>
<body style="background-image: url('https://images.unsplash.com/photo-1513605177423-fecee1533c2e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c2ltcGxlJTIwbGFuZHNjYXBlfGVufDB8fDB8fA%3D%3D&w=1000&q=80');">

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-md-offset-5 col-md-4 text-center">
            <h1 class='text-white'>Users Login Form</h1>
              <div class="form-login"></br>
                <h4>User Login</h4>
                </br>
                <input type="text" id="userName" class="form-control input-sm chat-input" placeholder="username"/>
                </br></br>
                <input type="password" id="userPassword" class="form-control input-sm chat-input" placeholder="password"/>
                <input type="checkbox" onclick="myFunction()" class="h1"><label class="lead ml-2 ">Show Password</label>
                                <script>
                                    function myFunction() {
                                        var x = document.getElementById("userPassword");
                                        if (x.type === "password") {
                                            x.type = "text";
                                        } else {
                                            x.type = "password";
                                        }
                                    }

        
                                    
                                </script>
                </br></br>
                <div class="wrapper">
                        <span class="group-btn">
                            <a href="#" class="btn btn-danger btn-md" id="loginBTN">login <i class="fa fa-sign-in"></i></a>
                        </span>
                </div>
                <label for="" class="lead" id="result"></label>
                <br><br>
                <div class="col">
                    <h4><a href="http://localhost:8080/signup/lg" class="text-warning">Create Account?</a></h4>
                </div>
            </div>
        </div>
    </div>
    </br></br></br>
    <!--footer-->
    <!-- <div class="footer text-white text-center">
        <p>© 2020 Unique Login Form. All rights reserved | Design by <a href="https://freecss.tech">Free Css</a></p>
    </div> -->
    <!--//footer-->
</div>
</body>
</html>
