<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Product Listing</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

  <div class="h2 text-center text-primary">Order Listing</div><br>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Order ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">address</th>
        <th scope="col">zipcode</th>
        <th scope="col">Product Name</th>

      </tr>
    </thead>
    <tbody>
      <?php
      // echo "<pre>";
      // print_r($arr2);
      $htm = "";
      foreach ($data as $key => $value) {
        $htm .= "
          <tr>
            <th scope='row'>$value->id</th>
            <td>$value->coustomerName</td>
            <td>$value->address</td>
            <td>$value->zipcode</td>
            <td>$value->Name</td>
        </tr>";
      }
      echo $htm;
      ?>

    </tbody>
  </table>

</body>

</html>