<?php
echo "<pre>";
print_r($this->request->getPost());
$arr = Role::find();
// print_r($arr);

echo "</pre>";

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup Page</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>

    <div class="h1 text-center text-primary">Signup User</div>
    <form class="" method="post">

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email">
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Password" name="password">
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Confirm Password" name="cpassword">
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <select class="form-select" aria-label="Default select example" name="role">
                    <option selected>Select Role</option>
                    <?php
                    $htm = "";
                    $arr = Role::find();
                    foreach ($arr as $key => $value) {
                        $htm .= "<option value=$value->role>$value->role</option>";
                    }
                    // die($htm);
                    echo $htm;
                    ?>

                </select>
            </div>
        </div>



        <div class="row d-flex justify-content-center">
            <div class="col-1">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <!-- <div class="h1">sbdjksdbb</div> -->
    </form>
</body>

</html>